### ISSUE TITLE
Concepts Insights - "ids" parameter of getConceptsMetadata() 

### ISSUE THREAD

**Issue by kajaldas007** [watson-developer-cloud/nodejs-wrapper#10]
I tried setting the "ids" parameter to:
1) just a string containing a single concept id
2) a string containing multiple concept ids separated by comma
3) an array of strings, each string for one concept id

but, each case, I got the following error:

{ error: 'invalid ids parameter', url: '' }

**Comment by germanattanasio** [comment]
`ids` its a stringify array of strings, something like:

```js
var watson = require('watson-developer-cloud');

var conceptInsights = watson.concept_insights({
  username: 'INSERT YOUR USERNAME FOR THE CONCEPT INSIGHTS SERVICE HERE',
  password: 'INSERT YOUR PASSWORD FOR THE CONCEPT INSIGHTS SERVICE HERE',
  version: 'v1'
});

var payload = {
  func: 'semanticSearch',
  ids: [
    '/graph/wikipedia/en-20120601/Software_development_process',
    '/graph/wikipedia/en-20120601/Programming_tool'
  ],
  corpus: 'ibmresearcher',
  user: 'public',
  limit: 5

};

// ids needs to be stringify
payload.ids = JSON.stringify(payload.ids);

conceptInsights.semanticSearch(payload, function(error, results) {
  if (error)
    console.log(error);
  else
    console.log(JSON.stringify(results, null, 2));
});
```

**Comment by nfriedly** [comment]
@germanattanasio I think that we should detect this and automatically fix it in the wrapper - I'd even go as far as to say that a non-stringified array should be the officially correct way to pass the payload to the wrapper. 

(Part of point of a wrapper is to hide ugly things like this and let users just pass in data in formats that make sense.)
