### ISSUE TITLE
Update Tradeoff-Analytics to the GA instance

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/nodejs-wrapper#21]
Since Tradeoff Analytics is GA we need to update the wrapper to point to the new url:
```
https://gateway.watsonplatform.net/tradeoff-analytics/api
```

This change will break existing apps using the beta service so, yhe change should be done once the beta service is removed.

**Comment by germanattanasio** [comment]
@jsstylos let me know what you think.

**Comment by nfriedly** [comment]
I think we should probably update to the new url on release day. If you want to keep old apps working, then perhaps we should rename the beta services to something like 'v1-beta'. (Or else just call the GA version 'v2' since having a different URL is a breaking change.)

**Comment by germanattanasio** [comment]
According to the WDC documentation. This change should be applied on June 28 which is when the Beta service will be removed.

**Comment by germanattanasio** [comment]
Fixed in 2978463790d8cf75f5e1b45b4ecb00eed60231a9
