### ISSUE TITLE
lib/index.js bug?

### ISSUE THREAD

**Issue by zimb-hase** [watson-developer-cloud/nodejs-wrapper#3]
Hi,

Under ver.0.9.3, I think I've found some bugs in lib/index.js file.

line 39:
```javascript
    if (typeof(user_options.use_vcap_services))
```
I think this should be;
```javascript
    if (user_options.use_vcap_services)
```
because, `typeof(user_options.use_vcap_services)` is always true.

line 42:
```javascript
    var options = extend(service.credentials, user_options);
```
I think this should be;
```javascript
    var options = extend(user_options, service.credentials);
```
because, whether `use_vcap_services` is true or not, `user_options` always overwrites the `service.credentials`. I believe you want `service.credentials`'s values to overwrite `user_options`'s value when `use_vcap_services` is true.

**Comment by germanattanasio** [comment]
Tests are ok and the fix seems to be working so I'm closing this,

Thanks @zimb-hase!
