### ISSUE TITLE
Update speech to text and text to speech examples

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/nodejs-wrapper#32]
Update the `README.md` and the examples in the `examples` folder.

**Comment by germanattanasio** [comment]
@esbullington can you help me with this?

**Comment by esbullington** [comment]
Yes, glad to.  Let me get the demo apps tested with the production services, and then deployed (which we'll need your help with, please, since you have the credentials), and then I'll take care of this.

**Comment by germanattanasio** [comment]
Fixed in cec3cf4d791c3deb09a14f95fdecc18f36575f81
