### ISSUE TITLE
Differentiate between beta and GA credentials

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/nodejs-wrapper#35]
Right now the code that looks for credentials (getServiceCreds) for a service in VCAP_SERVICES doesn't differentiate between beta and GA credentials, which means that even if you specify the correct local GA credentials, if the environment variable contains beta credentials, the incorrectly matched environment variable credentials will take precedence, preventing the code from working. getServiceCreds should also take a version from which it can determine if a GA service is being used and check the plan to avoid false matches.

**Comment by germanattanasio** [comment]
I've fixed this in [vcap_services](https://www.npmjs.com/package/vcap_services), the library we use to get credentials from bluemix.
