### ISSUE TITLE
Add scorecard support to the Tone Analyzer service

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/nodejs-wrapper#48]
I went to the api documentation for Tone Analyzer (http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/apis/tone-analyzer-apis.html). I never saw `/scorecards` before and it doesn't 's have support in the wrapper.
@herchu is `/scorecards` supported by the api? Do we need to add it to the wrapper?  if yes, can you do it?

**Comment by germanattanasio** [comment]
fixed

**Comment by loorinm** [comment]
Are there alternative scorecards other than "email"?

**Comment by germanattanasio** [comment]
not at the moment but the team is working on more scorecards
