### ISSUE TITLE
Add licenses for dependencies in repo

### ISSUE THREAD

**Issue by gjs29** [watson-developer-cloud/nodejs-wrapper#52]
The repo should include licenses for dependencies. This should include the newly added solr-client: https://www.npmjs.com/package/solr-client

**Comment by germanattanasio** [comment]
Most of the dependencies we have are using MIT but we don't list/describe them in our readme. This is mandatory for IBM projects.

**Comment by germanattanasio** [comment]
Looks like if the dependency is not included in the source code we don't need to list it in the README.md  
In this case `sorl-client` is installed via `npm` not shipped with this source code.
