### ISSUE TITLE
Add Alchemy APIs

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/nodejs-wrapper#72]
Add Alchemy APIs to the wrapper:

- [x] Alchemy Language
- [x] Alchemy Vision
- [x] Alchemy Data

**Comment by nfriedly** [comment]
We can base alchemy news off of @danielchengibm's work in https://github.com/watson-developer-cloud/company-insights/blob/master/src/server/watson.js#L37

**Comment by germanattanasio** [comment]
I need to fix alchemy vision and add the examples for Vision and Data news

**Comment by germanattanasio** [comment]
everything is working in 0.10.4
