### ISSUE TITLE
Natural Language Classifier url has beta

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/nodejs-wrapper#79]
in /services/natural_language_classifier/v1.js

var serviceDefaults = {
    url: 'https://gateway.watsonplatform.net/natural-language-classifier-beta/api'
  };

**Comment by jsstylos** [comment]
This is related to #43, differentiating beta and GA versions of a service. Right now the default is kept until beta to avoid breaking beta users until the beta service is turned off. However, we should differentiate in the version when the beta version of a service is requested.
