### ISSUE TITLE
Relationship extraction  - "limit" parameter

### ISSUE THREAD

**Issue by kajaldas007** [watson-developer-cloud/nodejs-wrapper#8]
Which part of the response (e.g. Mentions, entities or relations) is controlled by the parameter "limit" ? 
I have tried setting this parameter to different values; but the result looks the same always.

**Comment by germanattanasio** [comment]
There is no limit parameter in relationship extraction.

**Comment by kajaldas007** [comment]
Sorry about that. I must have confused this with some other API..
