### ISSUE TITLE
Use `npm version` for releases rather than manually changing the package.json version

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/nodejs-wrapper#81]
Standard practice with node.js modules is to commit all of the changes for a release *except updating the package.json version*, and then run the following:

```sh
npm version major|minor|patch
git push --tags
npm publish
```
`npm version *` will update the package.json version field appropriately *and* create a git commit and tag for the version.  `git push --tags` will publish the tag to github, and then immediately running `npm publish` ensures no changes have a chance to sneak in.

The reason for this is that it allows someone to easily view the source code (and readme) for whatever version they happen to have downloaded from npm. This is particularly helpful when github is ahead of npm - right now there isn't any straightforward way to view what git commit matches the current npm release.

**Comment by germanattanasio** [comment]
:+1:

**Comment by germanattanasio** [comment]
for future releases I did:
```
npm version patch
git push --tags
git push origin master
npm publish
```

**Comment by nfriedly** [comment]
looks good to me. Sometimes we'll want to do `npm version minor` and eventually `npm version major` - (the version number is major.minor.patch - see http://semver.org/ for details.)

**Comment by germanattanasio** [comment]
I added this info in 91a07275da5b713422e463bd4076535e510d2892. Closing this since it's now part of our release process
