### ISSUE TITLE
Remove Machine Translation and Language Identification stubs

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/nodejs-wrapper#82]
Now that these services have been discontinued for some time, I propose that we remove the nearly empty service stubs so that users do see these in the directory listing.

**Comment by germanattanasio** [comment]
I updated the code to display a DEPRECATED message and point users to use the correct service. 
This was a few weeks ago so I will proposed to keep it 1 or 2 more weeks.

**Comment by nfriedly** [comment]
I'd recommend keeping an explanation somewhere, but a footnote in the readme is probably sufficient.
