### ISSUE TITLE
Natural Language Classifier classifier parameter should be classifier_id

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/nodejs-wrapper#84]
The classifier code uses `classifier` for a parameter for classifier, status, and remove. If there isn't a specific reason, it should match the REST code and be `classifier_id`

**Comment by germanattanasio** [comment]
I sure this was my fault... anyway I will add classifier_id as an accepted parameter and make both work for a while. Users will be able to specify either `classifier` or `classifier_id`

**Comment by SirSpidey** [comment]
Thanks @germanattanasio. I'll look for the updates and then update the API ref at http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/natural-language-classifier/api/v1/

**Comment by germanattanasio** [comment]
fixed in e8d9ddfe19a8f98cb3a8a18e75deadefb6f2d89d
